// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zxbztnfskxrlnpgzofff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Ynp0bmZza3hybG5wZ3pvZmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NzA5NTIsImV4cCI6MjA3NjM0Njk1Mn0.JAB6U9dPDyQGt4f6G0sQKZ0MRQbSiIifoxieuRLBRoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);